name: Pack Flet App

on:
  workflow_dispatch:

env:
  UV_PYTHON: 3.11   # Python version
  PYTHONUTF8: 1

  # https://docs.flet.dev/publish/
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # https://docs.flet.dev/reference/environment-variables
  FLET_CLI_NO_RICH_OUTPUT: 1

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # -------- Desktop --------
          - name: linux
            runner: ubuntu-latest
            build_cmd: "flet pack main.py --distpath linux --name csv2latex"
            artifact_path: linux/csv2latex
            needs_linux_deps: true

          - name: macos
            runner: macos-latest
            build_cmd: "flet pack main.py --distpath macos --name csv2latex"
            artifact_path: macos/csv2latex
            needs_linux_deps: false

          - name: windows
            runner: windows-latest
            build_cmd: "flet pack main.py --distpath windows --name csv2latex"
            artifact_path: windows/csv2latex.exe
            needs_linux_deps: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Linux dependencies
        if: matrix.needs_linux_deps
        shell: bash
        run: |
          sudo apt update --allow-releaseinfo-change
          sudo apt-get install -y --no-install-recommends \
            clang \
            ninja-build \
            libgtk-3-dev \
            libasound2-dev \
            libmpv-dev \
            mpv \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            gstreamer1.0-alsa \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-qt5 \
            gstreamer1.0-pulseaudio \
            pkg-config \
            libsecret-1-0 \
            libsecret-1-dev
          sudo apt-get clean

      - name: Pack app
        shell: bash
        run: |
          uv run ${{ matrix.build_cmd }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ${{ matrix.name }}-build-artifact
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error
          overwrite: false